export PATH="${HOME}/bin:${PATH}"                     # roll my own
# export PATH="${HOME}/tools/flutter/bin:${PATH}"       # flutter
export PATH="/opt/local/bin:/opt/local/sbin:${PATH}"  # macports
export PATH="/opt/local/libexec/gnubin/:${PATH}"      # gnu versions of coreutils
export PATH=${HOME}/bin:/opt/local/libexec/gnubin:/opt/local/bin:${HOME}/go/bin:${PATH}

# https://ss64.com/bash/syntax-prompt.html
# => man terminfo and search for "These are the string capabilities:"
# export PS1='[\e[0;36m\u@\h\e[0m \w$(__git_ps1 " (%s)")]\$ '
cyan=$(tput setaf 6)
green=$(tput setaf 2)
reset=$(tput sgr0) # reset to default color, this was not the same as the URL shows
export PS1='[\[${cyan}\]\u@\h\[${reset}\] \w\[$green\]$(__git_ps1 " (%s)")\[${reset}\]]\$ '


# https://stackoverflow.com/questions/15883416/adding-git-branch-on-the-bash-command-prompt#24716445
if [ -f /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh ]; then
	. /Library/Developer/CommandLineTools/usr/share/git-core/git-prompt.sh
fi

#if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
#	source /usr/local/share/chruby/chruby.sh
#	RUBIES+=(
#		"$HOME/src/ruby-2.7.4"
#	)
#	# set default
#	chruby 2.7.4
#	source /usr/local/share/chruby/auto.sh
#
#	source /usr/local/share/gem_home/gem_home.sh
#fi

if [ -f $HOME/.bash_aliases ]; then
	. $HOME/.bash_aliases
fi

if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
	. /opt/local/etc/profile.d/bash_completion.sh
fi 

if [ -f "${HOME}/.asdf/asdf.sh" ]; then
	. "${HOME}/.asdf/asdf.sh"
fi 

if [ -f "${HOME}/.asdf/completions/asdf.bash" ]; then
	. "${HOME}/.asdf/completions/asdf.bash"
fi 

# Keep asdf/flutter quiet if not installed
FLUTTER_ROOT=$(asdf where flutter 2>/dev/null)
if [ "x" != "x${FLUTTER_ROOT}" ]; then
	export FLUTTER_ROOT
fi

# Couldn't do this with aliases
function tf() {
	clear
	echo "terraform $@"
	terraform $@
}

# Add completion to terraform and my shell function shortcut
# https://developer.hashicorp.com/terraform/cli/commands#shell-tab-completion
# use terraform -install-completion
#complete -C /opt/local/bin/terraform tf
#complete -C /opt/local/bin/terraform terraform

# nomad completion
complete -C ${HOME}/bin/nomad nomad

. ~/bin/task_darwin_arm64/completion/bash/task.bash

export PATH="/usr/local/bin:$PATH"

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"
